name: E2E Test

on: [pull_request]

jobs:
  e2e-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright Browsers
        run: pnpm test:e2e:install

      - name: Build and E2E Test
        run: pnpm test:e2e:build
